# Generated by Django 4.2 on 2025-04-17 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("category", "0001_initial"),
        ("card", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BudgetModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created DateTime")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated DateTime")),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("period", models.DateField(verbose_name="Period")),
                ("limit", models.IntegerField(verbose_name="Limit")),
                ("spent", models.IntegerField(verbose_name="Spent")),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget",
                        to="card.cardmodel",
                        verbose_name="Card",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget",
                        to="category.categorymodel",
                        verbose_name="Category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="budget",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Budget",
                "verbose_name_plural": "Budgets",
                "ordering": ("-created_at",),
            },
        ),
    ]
