# Generated by Django 4.2 on 2025-04-08 15:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CardModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created DateTime")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated DateTime")),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("balance", models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name="Balance")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="card",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Card",
                "verbose_name_plural": "Cards",
                "ordering": ("-created_at",),
            },
        ),
    ]
