# Generated by Django 4.2 on 2025-04-20 12:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("category", "0001_initial"),
        ("card", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IncomeModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created DateTime")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated DateTime")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="Amount")),
                ("description", models.TextField(blank=True, null=True, verbose_name="Description")),
                ("date", models.DateField(auto_now_add=True, null=True, verbose_name="Date")),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incomes",
                        to="card.cardmodel",
                        verbose_name="Card",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="incomes",
                        to="category.categorymodel",
                        verbose_name="Category",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="incomes",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Income",
                "verbose_name_plural": "Incomes",
                "ordering": ("-date",),
            },
        ),
    ]
