# Generated by Django 4.2 on 2025-04-20 12:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("income", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="incomemodel",
            options={"ordering": ("-category",), "verbose_name": "Income", "verbose_name_plural": "Incomes"},
        ),
        migrations.AlterField(
            model_name="incomemodel",
            name="date",
            field=models.DateField(blank=True, null=True, verbose_name="Date"),
        ),
    ]
