# Generated by Django 4.2 on 2025-04-17 17:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoryModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created DateTime")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated DateTime")),
                ("title_en", models.CharField(max_length=255, verbose_name="Title in English")),
                ("title_ru", models.CharField(max_length=255, verbose_name="Title in Russian")),
                ("title_ky", models.CharField(max_length=255, verbose_name="Title in Kyrgyz")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ("-created_at",),
            },
        ),
    ]
