# Generated by Django 4.2 on 2025-04-20 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("card", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoalModel",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Created DateTime")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated DateTime")),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("period", models.DateField(verbose_name="Period")),
                ("goal", models.IntegerField(verbose_name="Goal")),
                ("current", models.IntegerField(blank=True, default=0, null=True, verbose_name="Current Capacity")),
                (
                    "card",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goal",
                        to="card.cardmodel",
                        verbose_name="Card",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goal",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="User",
                    ),
                ),
            ],
            options={
                "verbose_name": "Goal",
                "verbose_name_plural": "Goals",
                "ordering": ("-created_at",),
            },
        ),
    ]
